// Generated by LiveScript 1.2.0
(function(){
  var define, slice$ = [].slice;
  define = (typeof window != 'undefined' && window !== null ? window.define : void 8) || require('amdefine')(module);
  define(function(require, exports, module){
    var lodash, Component, ParallaxButton, SiteRegister, sh, templates, debounce, Sales;
    lodash = require('lodash');
    Component = require('yacomponent');
    ParallaxButton = require('./ParallaxButton');
    SiteRegister = require('./SiteRegister');
    sh = require('../shared/shared-helpers');
    templates = require('../build/component-jade').templates;
    debounce = partialize$.apply(lodash, [lodash.debounce, [void 8, 250], [0]]);
    return module.exports = Sales = (function(superclass){
      var prototype = extend$((import$(Sales, superclass).displayName = 'Sales', Sales), superclass).prototype, constructor = Sales;
      prototype.template = templates.Sales;
      prototype.init = function(){
        this.local('subdomain', '');
        return this.children = {
          registerTop: new SiteRegister({
            locals: {
              subdomain: this.state.subdomain
            }
          }, '#register_top', this),
          registerBottom: new SiteRegister({
            locals: {
              subdomain: this.state.subdomain
            }
          }, '#register_bottom', this)
        };
      };
      prototype.onAttach = function(){
        var this$ = this;
        return constructor.$R(function(subdomain){
          var i$, ref$, len$, c, results$ = [];
          for (i$ = 0, len$ = (ref$ = [this$.children.registerTop, this$.children.registerBottom]).length; i$ < len$; ++i$) {
            c = ref$[i$];
            results$.push(c.updateSubdomain(subdomain));
          }
          return results$;
        }).bindTo(this.state.subdomain);
      };
      function Sales(){
        Sales.superclass.apply(this, arguments);
      }
      return Sales;
    }(Component));
  });
  function partialize$(f, args, where){
    var context = this;
    return function(){
      var params = slice$.call(arguments), i,
          len = params.length, wlen = where.length,
          ta = args ? args.concat() : [], tw = where ? where.concat() : [];
      for(i = 0; i < len; ++i) { ta[tw[0]] = params[i]; tw.shift(); }
      return len < wlen && len ?
        partialize$.apply(context, [f, ta, tw]) : f.apply(context, ta);
    };
  }
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
