// Generated by LiveScript 1.2.0
(function(){
  var define;
  define = (typeof window != 'undefined' && window !== null ? window.define : void 8) || require('amdefine')(module);
  define(function(require, exports, module){
    var Auth, Component, Sales, templates, SalesLayout;
    Auth = require('./Auth');
    Component = require('yacomponent');
    Sales = require('./Sales');
    templates = require('../build/component-jade').templates;
    return module.exports = SalesLayout = (function(superclass){
      var prototype = extend$((import$(SalesLayout, superclass).displayName = 'SalesLayout', SalesLayout), superclass).prototype, constructor = SalesLayout;
      prototype.template = templates.SalesLayout;
      prototype.login = function(user){
        this.$.find('li.auth a.onclick-login').hide();
        return this.$.find('li.auth a.onclick-logout').show();
      };
      prototype.logout = function(){
        this.$.find('li.auth a.onclick-login').show();
        return this.$.find('li.auth a.onclick-logout').hide();
      };
      function SalesLayout(){
        SalesLayout.superclass.apply(this, arguments);
      }
      return SalesLayout;
    }(Component));
  });
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
