// Generated by LiveScript 1.2.0
(function(){
  var define;
  define = (typeof window != 'undefined' && window !== null ? window.define : void 8) || require('amdefine')(module);
  define(function(require, exports, module){
    var Component, Sales, templates, SalesApp;
    Component = require('yacomponent');
    Sales = require('./Sales');
    templates = require('../build/component-jade').templates;
    return module.exports = SalesApp = (function(superclass){
      var prototype = extend$((import$(SalesApp, superclass).displayName = 'SalesApp', SalesApp), superclass).prototype, constructor = SalesApp;
      prototype.template = templates.SalesApp;
      prototype.init = function(){
        return this.children = {
          sales: new Sales({}, '.SalesApp-content', this)
        };
      };
      prototype.onAttach = function(){
        return constructor.$('.Sales-subdomain:first').focus();
      };
      prototype.login = function(user){
        this.$.find('li.auth a.onclick-login').hide();
        return this.$.find('li.auth a.onclick-logout').show();
      };
      prototype.logout = function(){
        this.$.find('li.auth a.onclick-login').show();
        return this.$.find('li.auth a.onclick-logout').hide();
      };
      function SalesApp(){
        SalesApp.superclass.apply(this, arguments);
      }
      return SalesApp;
    }(Component));
  });
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
